### ISSUE TITLE
Макс

### ISSUE THREAD

**Issue by Maksbeloziorov** [RedEyeCoffee/TheGame#20]
увеличить поле, добавить объекты.

пофиксить что бы не пересекались объекты.

**Comment by Kris465** [comment]
Баг с попаданием объектов друг в друга известен и уже описан в другой задаче. Можно ее взять и расширить по своему желанию при выполнении. Так как эта задача пересекается с другой, то я закрываю эту задачу. 
"Увеличить поле" и "Добавить объекты" - перенесены в дискусии-идеи.
